# Happy Coding!

service: ${file(./package.json):name}

plugins:
  - serverless-webpack
  - serverless-plugin-aws-alerts
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  logRetentionInDays: 30
  stage: ${opt:stage, env:ENV} # you can override this via the CLI argument
  apiKeys:
    - ${self:service}-key-${self:provider.stage}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  usagePlan:
    quota:
      limit: 2000
      period: MONTH
    throttle:
      burstLimit: 10
      rateLimit: 5
  environment: # Service wide environment variables
    STAGE: ${self:provider.stage}
    TEMPLATE_NAME: ${file(./templates/${env:TEMPLATE_NAME, "default-template"}.json):TemplateName}
    AWS_SES_REGION: ${env:AWS_SES_REGION, self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_SSM_PREFIX: /${self:service}/${self:provider.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendTemplatedEmail'
      Resource: 'arn:aws:ses:${self:provider.environment.AWS_SES_REGION}:${env:AWS_ACCOUNT_ID}:*'
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameter'
      Resource: 'arn:aws:ssm:${self:provider.region}:${env:AWS_ACCOUNT_ID}:parameter${self:provider.environment.AWS_SSM_PREFIX}/*'
    - Effect: 'Allow'
      Action:
        - 'kms:Decrypt'
      Resource: 'arn:aws:kms:${self:provider.region}:${env:AWS_ACCOUNT_ID}:key/CMK'

custom:
  period:
    development: 300
    production: 60
  enabled:
    development: false
    production: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # https://github.com/amplify-education/serverless-domain-manager
  customDomain:
    basePath: lambda-mail
    domainName: ${env:CUSTOM_DOMAIN}
    createRoute53Record: false
  # https://github.com/ACloudGuru/serverless-plugin-aws-alerts
  alerts:
    topics:
      alarm:
        topic: arn:aws:sns:eu-central-1:009255630476:alert-Topic-N47IM5J07MP7
    definitions: # these defaults are merged with your definitions
      functionThrottles:
        treatMissingData: notBreaching
        period: ${self:custom.period.${self:provider.stage}}
      functionErrors:
        treatMissingData: notBreaching
        period: ${self:custom.period.${self:provider.stage}}
      functionInvocations:
        threshold: 50
        treatMissingData: notBreaching
        period: ${self:custom.period.${self:provider.stage}}
      functionDuration:
        threshold: 4000
        treatMissingData: notBreaching
        period: ${self:custom.period.${self:provider.stage}}
      statusCodeErrors:
        metric: statusCodeErrors
        threshold: 0
        statistic: Sum
        period: ${self:custom.period.${self:provider.stage}}
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: '{$.statusCode != 200}'
        treatMissingData: missing
    alarms:
      - name: functionThrottles
        enabled: ${self:custom.enabled.${self:provider.stage}}
      - name: functionErrors
        enabled: true
      - name: functionInvocations
        enabled: true
      - name: functionDuration
        enabled: true
      - name: statusCodeErrors
        enabled: true

functions:
  sendmail:
    handler: handler.send
    events:
      - http:
          private: true
          cors: true
          path: send/{domain}
          method: POST
          request:
            parameters:
              paths:
                domain: true
  config:
    handler: handler.config
    alarms:
      - name: functionThrottles
        enabled: false
      - name: functionDuration
        enabled: false
      - name: functionErrors
        enabled: false
      - name: statusCodeErrors
        enabled: false
    events:
      - http:
          private: true
          cors: true
          path: /config/{domain}
          method: GET
