# Happy Coding!

service: api-mail

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: eu-central-1
  stage: dev # you can override this via the CLI argument
  environment: # Service wide environment variables
    STAGE: ${opt:stage}

functions:
  sendmail:
    handler: handler.sendmail
    events:
      - http:
          path: sendmail
          method: post