# Happy Coding!

service: api-mail

plugins:
  - serverless-plugin-include-dependencies
  - serverless-plugin-aws-alerts
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  region: eu-central-1
  stage: dev # you can override this via the CLI argument
  apiKeys:
    - ${self:service}-key-${self:custom.stage}
  usagePlan:
    quota:
      limit: 2000
      period: MONTH
    throttle:
      burstLimit: 10
      rateLimit: 5
  environment: # Service wide environment variables
    STAGE: ${self:custom.stage}
    TEMPLATE: ${self:custom.template}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: '*'

custom:
  # https://github.com/amplify-education/serverless-domain-manager
  stage: ${opt:stage, self:provider.stage}
  template: ${self:service}-template
  domains:
    production: lapi.johannroehl.de
    dev: dev-lapi.johannroehl.de
  customDomain:
    basePath: mail
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: false
  # https://github.com/ACloudGuru/serverless-plugin-aws-alerts
  alerts:
    topics:
      alarm:
        topic: arn:aws:sns:eu-central-1:009255630476:alert-Topic-N47IM5J07MP7
    definitions: # these defaults are merged with your definitions
      functionThrottles:
        treatMissingData: notBreaching
      functionErrors:
        treatMissingData: notBreaching
      functionInvocations:
        threshold: 50 # override threshold
        treatMissingData: notBreaching
      functionDuration:
        threshold: 4000 # override threshold
        treatMissingData: notBreaching
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

functions:
  sendmail:
    handler: handler.send
    events:
      - http:
          private: true
          cors: true
          path: mail/send/{domain}
          method: post
          request:
            parameters:
              paths:
                domain: true
