name: 'Test pull request changes'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'ci'
        run: npm ci
      - name: 'test'
        run: npm run test
